language: csharp
sudo: required
services:
  - docker
before_install:
- docker build -t veggerby/algorithm -f ./test/Dockerfile .
- docker run veggerby/algorithm dotnet test /app/test/Veggerby.Algorithm.Tests

script:
- dotnet test /app/test/Veggerby.Algorithm.Tests